/**
 * Writes api-base-url.js from VIRALZAPS_API_BASE_URL or RAZORPAY_API_BASE_URL (Vercel/Netlify/CI).
 * Preserves VIRALZAPS_LOCAL_API_BASE_URL from the existing api-base-url.js when present.
 * Run: npm run build
 */
const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, '..', 'api-base-url.js');

const hasInjectEnv =
  Object.prototype.hasOwnProperty.call(process.env, 'VIRALZAPS_API_BASE_URL') ||
  Object.prototype.hasOwnProperty.call(process.env, 'RAZORPAY_API_BASE_URL');
const url = (process.env.VIRALZAPS_API_BASE_URL || process.env.RAZORPAY_API_BASE_URL || '').trim();

if (!hasInjectEnv && fs.existsSync(out)) {
  console.log('inject-api-url: skipping (set VIRALZAPS_API_BASE_URL for production build)');
  process.exit(0);
}

let localBase = 'http://localhost:4000';
try {
  const existing = fs.readFileSync(out, 'utf8');
  const m = existing.match(/VIRALZAPS_LOCAL_API_BASE_URL\s*=\s*['"]([^'"]+)['"]/);
  if (m && m[1]) localBase = m[1].trim();
} catch (e) {
  /* use default */
}

const content =
  '// Auto-generated by npm run build; set VIRALZAPS_API_BASE_URL on your host\n' +
  '// Edit VIRALZAPS_LOCAL_API_BASE_URL in this file before build to change local dev port.\n' +
  '(function () {\n' +
  "  if (typeof window === 'undefined') return;\n" +
  `  window.VIRALZAPS_LOCAL_API_BASE_URL = ${JSON.stringify(localBase)};\n` +
  `  window.RAZORPAY_API_BASE_URL = ${JSON.stringify(url)};\n` +
  '  window.viralzapsLocalBackendPortRange = function () {\n' +
  "    var base = String(window.VIRALZAPS_LOCAL_API_BASE_URL || '');\n" +
  "    var m = base.match(/^https?:\\/\\/[^:]+:(\\d+)/);\n" +
  '    var start = m ? parseInt(m[1], 10) : 4000;\n' +
  '    if (isNaN(start)) start = 4000;\n' +
  '    return { start: start, end: start + 10 };\n' +
  '  };\n' +
  '})();\n';

fs.writeFileSync(out, content);
